name: 'Build and Push to Multiple Registries'

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: 'Build and Push LibreTV'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: 'Check out repository'
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0
          
      - name: 'Set Docker image tags'
        id: set-tag
        run: |
          echo "IMAGE_NAME=tvpro" >> $GITHUB_OUTPUT
          echo "SHORT_SHA=${GITHUB_SHA:0:7}" >> $GITHUB_OUTPUT

      - name: 'Set up Docker Buildx'
        uses: docker/setup-buildx-action@v3.10.0

      - name: 'Set up Docker QEMU'
        uses: docker/setup-qemu-action@v3.5.0

      # 推送到 GitHub Packages
      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v3.4.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 'Build and push to GHCR'
        uses: docker/build-push-action@v6.14.0
        with:
          context: .
          file: Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ steps.set-tag.outputs.IMAGE_NAME }}:latest
            ghcr.io/${{ github.repository_owner }}/${{ steps.set-tag.outputs.IMAGE_NAME }}:${{ steps.set-tag.outputs.SHORT_SHA }}
          platforms: linux/amd64,linux/arm64/v8
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # 推送到 Docker Hub
      - name: 'Login to Docker Hub'
        uses: docker/login-action@v3.4.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: 'Build and push to Docker Hub'
        uses: docker/build-push-action@v6.14.0
        with:
          context: .
          file: Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ steps.set-tag.outputs.IMAGE_NAME }}:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ steps.set-tag.outputs.IMAGE_NAME }}:${{ steps.set-tag.outputs.SHORT_SHA }}
          platforms: linux/amd64,linux/arm64/v8
